#!/bin/ash

# Includes
BASEDIR=$(dirname "$0")
. "$BASEDIR/constants"
. "$BASEDIR/utils"

# /cgi-bin/printer?start=filename
printer_on_start() {
    echo "~M23 0:/user/$1" | nc localhost 8899 2>/dev/null
    echo "Status: 200 OK"
}

# /cgi-bin/printer?cancel
printer_on_cancel() {
    echo "~M26" | nc localhost 8899 2>/dev/null
    echo "Status: 200 OK"
}

# /cgi-bin/printer?resume
printer_on_resume() {
    echo "~M24" | nc localhost 8899 2>/dev/null
    echo "Status: 200 OK"
}

# /cgi-bin/printer?pause
printer_on_pause() {
    echo "~M25" | nc localhost 8899 2>/dev/null
    echo "Status: 200 OK"
}

# /cgi-bin/printer?temperature
printer_on_temperature() {
    echo "Content-type: text/html"
    echo ""
    echo "~M105" | nc localhost 8899
}

# /cgi-bin/printer?status
printer_on_status() {
    echo "Content-type: text/html"
    echo ""
    echo "~M27" | nc localhost 8899
}

# /cgi-bin/printer?endstop
printer_on_endstop() {
    echo "Content-type: text/html"
    echo ""
    echo "~M119" | nc localhost 8899
}

# /cgi-bin/printer?camera
printer_on_camera() {
    echo "Content-type: text/html"
    echo ""
    utils_get_camera_url
}

# /cgi-bin/printer?camera-url-store=value
printer_on_camera_url_store() {
    mkdir -p $CONF_PATH
    echo "$1" > $CONF_PATH/camera-url.cfg
    echo "Status: 200 OK"
}

# /cgi-bin/printer?camera-url-clear
printer_on_camera_url_clear() {
    rm -rf $CONF_PATH/camera-url.cfg
    echo "Status: 200 OK"
}

# /cgi-bin/printer?lighton
printer_on_lighton() {
    echo "Content-type: text/html"
    echo ""
    echo "~M146 r255 g255 b255" | nc localhost 8899 2>/dev/null
    echo "Status: 200 OK"
}

# /cgi-bin/printer?lightoff
printer_on_lightoff() {
    echo "Content-type: text/html"
    echo ""
    echo "~M146 r0 g0 b0" | nc localhost 8899 2>/dev/null
    echo "Status: 200 OK"    
}

# Parse Requests
if [ -z "$QUERY_STRING" ]; then
    echo "Status: 400 Bad Request"
    exit 1
else
    IFS="&"
    set -- $QUERY_STRING
    key="${1%=*}"
    if [ "$key" = "start" ]; then
        printer_on_start "${1#*=}"
    elif [ "$key" = "cancel" ]; then
        printer_on_cancel
    elif [ "$key" = "resume" ]; then
        printer_on_resume
    elif [ "$key" = "pause" ]; then
        printer_on_pause
    elif [ "$key" = "temperature" ]; then
        printer_on_temperature
    elif [ "$key" = "status" ]; then
        printer_on_status
    elif [ "$key" = "endstop" ]; then
        printer_on_endstop
    elif [ ${key} == "camera-url-store" ]; then
        printer_on_camera_url_store "${1#*=}"
    elif [ ${key} == "camera-url-clear" ]; then
        printer_on_camera_url_clear
    elif [ "$key" = "camera" ]; then
        printer_on_camera
    elif [ "$key" = "lighton" ]; then
        printer_on_lighton
    elif [ "$key" = "lightoff" ]; then
        printer_on_lightoff
    else
        echo "Status: 400 Bad Request"
        exit 1
    fi
fi
