#!/bin/ash

# Includes
. ./constants
. ./utils

# Handlers
on_camera() {
    echo "Content-type: text/html"
    echo ""
    utils_get_camera_url
}

# Parse Request: cgi-bin/status?camera
if [ -z $QUERY_STRING ]; then
    return "Status: 400 Bad Request"
else
    IFS="&"
    set -- $QUERY_STRING
    key="${1%=*}"
    if [ ${key} == "camera" ]; then
        on_camera
    fi
fi
